title: <p align="center">Janette Le</p> # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
      <p align="center"><a href="https://www.linkedin.com/in/uyen-le-janette-a105b4172/">LinkedIn | </a> <a href="https://janette-le.github.io/">GitHub | </a>  <a href="https://drive.google.com/file/d/1Tm1xuQJDurg7Cu74e8e9av1JPvh6P5U9/view?usp=sharing">Resume</a></p> 
      <p align="center">
      First description
      Second description</p>
      
theme: jekyll-theme-minimal


