title: <p align="center">Janette Le</p> # your name (or website title) here
logo: "/images/circle-cropped.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
      <p align="center"><a href="https://www.linkedin.com/in/uyen-le-janette-a105b4172/">LinkedIn | </a> <a href="https://janette-le.github.io/">GitHub | </a>  <a href="https://drive.google.com/file/d/1Tm1xuQJDurg7Cu74e8e9av1JPvh6P5U9/view?usp=sharing">Resume</a></p> 
      <p align="justify">Passionate and motivated by data science where I can extract and deploy insights hidden underneath raw data. These insights can be applied to deliver business value, increase profit margin, or ameliorate operational processes. No one can deny how powerful data can be, but dominating big data requires us to keep ourselves up-to-date with new techniques every single day. From simple to complicated ideas, from small to comprehensive projects, I try to be a better me than yesterday.</p>

theme: jekyll-theme-minimal

